# -*- coding: utf-8 -*-
"""PKK web_scrape.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1icLt_5o-8-YFXlVoF9R2sau-D51h65K4
"""

# @title Install Selenium
# !pip3 install selenium undetected-chromedriver
# !pip3 install selenium

# @title Download Chromedriver
# !apt-get update
# !apt-get install -y wget unzip
# !wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# !dpkg -i google-chrome-stable_current_amd64.deb
# !apt-get install -f
# !wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
# !unzip chromedriver_linux64.zip
# !mv chromedriver /usr/local/bin/
# !chmod +x /usr/local/bin/chromedriver

# @title Install webdriver
# !pip3 install webdriver-manager

# @title Dawis
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time
import pandas as pd

chrome_driver_path = "/usr/local/bin/chromedriver/chrome"
# Konfigurasi opsi Chrome
chrome_options = Options()
chrome_options.add_argument("--headless")  # Menjalankan Chrome dalam mode headless
# chrome_options.add_argument("--no-sandbox")
# chrome_options.add_argument("--disable-dev-shm-usage")
# chrome_options.add_argument("--disable-javascript")


# Inisialisasi driver Chrome
driver_service = Service(executable_path=chrome_driver_path)
driver = webdriver.Chrome(service=driver_service, options=chrome_options)

# Inisialisasi WebDriver (sesuaikan path ke ChromeDriver Anda)
# driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)
# driver = webdriver.Chrome(service=Service(chromedriver_path.install()), options=chrome_options)



try:
    # Buka URL halaman login
    driver.get("https://simpkk.kabsemarangtourism.id/index.php/login")

        # Tunggu hingga elemen input username muncul
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.NAME, "username"))
    )

    # Temukan elemen input untuk username
    username_input = driver.find_element(By.NAME, "username")
    # Isi input username
    username_input.send_keys("sumowono")

    # Temukan elemen input untuk password
    password_input = driver.find_element(By.NAME, "password")
    # Isi input password
    password_input.send_keys("123")

    # Temukan tombol Sign In dengan tag <button>
    sign_in_button = driver.find_element(By.XPATH, "//button[text()='Sign In']")

    # Klik tombol Sign In
    sign_in_button.click()

    # Navigasi ke halaman yang diperlukan
    driver.get("https://simpkk.kabsemarangtourism.id/admin/dawis")

    # Tunggu hingga tabel muncul
    WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH, "//table[@id='dataTable']")))

    # Temukan elemen select dan pilih jumlah entri
    select_elem = driver.find_element(By.NAME, "dataTable_length")
    select = Select(select_elem)
    driver.execute_script("arguments[0].innerHTML += '<option value=\"20000\">20000</option>';", select_elem)
    select.select_by_value('20000')

    # Tunggu beberapa saat untuk memastikan tabel baru dimuat
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, "//table[@id='dataTable']/tbody/tr")))

    # Ambil data dari tabel
    rows = driver.find_elements(By.XPATH, "//table[@id='dataTable']/tbody/tr")
    
    data = []
    for row in rows:
        cols = row.find_elements(By.TAG_NAME, "td")
        data.append({
            "Nama_Kecamatan": cols[0].text,
            "Nama_Desa/Kelurahan": cols[1].text
        })

    # Convert data ke DataFrame
    df = pd.DataFrame(data)

    # Hitung jumlah entri per desa
    desa_counts = df['Nama_Desa/Kelurahan'].value_counts()

    # Buat DataFrame untuk hasil akhir
    data_summary = {
        "Desa": desa_counts.index,
        "Jumlah": desa_counts.values
    }
    df_summary = pd.DataFrame(data_summary)

    # Tampilkan DataFrame
    df_summary.index = df_summary.index + 1
    print(df_summary)

finally:
    # Tutup browser
    driver.quit()

# # @title Rekap KK dan Warga Sim PKK Kec.Sumowono
# # prompt: gabungkan output dari title Desa (Kebonagung, Candigaron, Ngadikerso, Lanjan, Jubelan, Sumowono, Trayu, Kemitir, Duren, Pledokan, Mendongan, Bumen, Losari, Kemawi, Piyanggang, Keseneng), dan tampilkan dalam data frame namun khusus Desa Sumowono password "sumowono123" dan Desa Ngadikerso password "12345", hapus "Showing 1 to 10"

# from selenium import webdriver
# from selenium.webdriver.common.by import By
# from selenium.webdriver.chrome.service import Service
# from selenium.webdriver.chrome.options import Options
# from selenium.webdriver.support.ui import WebDriverWait, Select
# from selenium.webdriver.support import expected_conditions as EC
# from selenium.webdriver.common.keys import Keys
# from webdriver_manager.chrome import ChromeDriverManager
# import time
# from selenium.webdriver.support.ui import WebDriverWait
# import pandas as pd

# # Data desa
# data_desa = [
#     {"nama": "Kebonagung", "username": "kebonagungsumowono", "password": "123"},
#     {"nama": "Candigaron", "username": "candigaronsumowono", "password": "123"},
#     {"nama": "Ngadikerso", "username": "ngadikersosumowono", "password": "12345"},
#     {"nama": "Lanjan", "username": "lanjansumowono", "password": "123"},
#     {"nama": "Jubelan", "username": "jubelansumowono", "password": "123"},
#     {"nama": "Sumowono", "username": "sumowonosumowono", "password": "sumowono123"},
#     {"nama": "Trayu", "username": "trayusumowono", "password": "123"},
#     {"nama": "Kemitir", "username": "kemitirsumowono", "password": "123"},
#     {"nama": "Duren", "username": "durensumowono", "password": "123"},
#     {"nama": "Pledokan", "username": "pledokansumowono", "password": "123"},
#     {"nama": "Mendongan", "username": "mendongansumowono", "password": "123"},
#     {"nama": "Bumen", "username": "bumensumowono", "password": "123"},
#     {"nama": "Losari", "username": "losarisumowono", "password": "123"},
#     {"nama": "Kemawi", "username": "kemawisumowono", "password": "123"},
#     {"nama": "Piyanggang", "username": "piyanggangsumowono", "password": "123"},
#     {"nama": "Keseneng", "username": "kesenengsumowono", "password": "123"}
# ]

# chrome_driver_path = "D:\\Project Python\\chromedriver-win64\\chromedriver.exe"
# # Konfigurasi opsi Chrome
# chrome_options = Options()
# chrome_options.add_argument("--headless")  # Menjalankan Chrome dalam mode headless
# chrome_options.add_argument("--no-sandbox")
# chrome_options.add_argument("--disable-dev-shm-usage")
# # chrome_options.add_argument("--disable-javascript")


# # Inisialisasi driver Chrome
# driver_service = Service(executable_path=chrome_driver_path)
# driver = webdriver.Chrome(service=driver_service, options=chrome_options)

# # List untuk menyimpan hasil
# hasil = []

# try:
#     for desa in data_desa:
#         # Buka URL halaman login
#         driver.get("https://simpkk.kabsemarangtourism.id/index.php/login")

#         # Tunggu hingga elemen input username muncul
#         WebDriverWait(driver, 10).until(
#             EC.presence_of_element_located((By.NAME, "username"))
#         )

#         # Isi username dan password
#         username_input = driver.find_element(By.NAME, "username")
#         username_input.send_keys(desa["username"])
#         password_input = driver.find_element(By.NAME, "password")
#         password_input.send_keys(desa["password"])

#         # Klik tombol Sign In
#         sign_in_button = driver.find_element(By.XPATH, "//button[text()='Sign In']")
#         sign_in_button.click()

#         WebDriverWait(driver, 10)

#         # Pindah ke halaman KRT
#         driver.get("https://simpkk.kabsemarangtourism.id/users/registrasi")
#         WebDriverWait(driver, 10)
#         jml_krt = driver.find_element(By.XPATH, "//div[@class='dataTables_info']").text

#         # Pindah ke halaman warga TP PPK
#         driver.get("https://simpkk.kabsemarangtourism.id/users/userslistwarga")
#         WebDriverWait(driver, 10)
#         jml_warga = driver.find_element(By.XPATH, "//div[@class='dataTables_info']").text

#         # Simpan hasil
#         hasil.append({
#             "Desa": desa["nama"],
#             "KRT": jml_krt.replace("Showing 1 to 10 of ", "").replace(" entries", "").replace(",", ""),
#             "Warga_TP_PPK": jml_warga.replace("Showing 1 to 10 of ", "").replace(" entries", "").replace(",", "")
#         })

# finally:
#     # Tutup browser
#     driver.quit()

# # Buat DataFrame dari hasil
# df2 = pd.DataFrame(hasil)
# df2.index = df2.index + 1
# print(df2)

# # @title Rekap Dawis, KK, Warga SIP PKK
# # prompt: gabungkan hasil dari data frame dawis, KRT dan Warga TP PPK

# import pandas as pd
# # Assuming df1 is the DataFrame from the "Rekap Dawis" section
# # Assuming df2 is the DataFrame from the "Rekap KK dan Warga Sim PKK Kec.Sumowono" section
# # prompt: cetak tanggal dan waktu area indonesia

# from datetime import datetime
# import pytz

# # Dapatkan zona waktu Asia/Jakarta
# tz_ID = pytz.timezone('Asia/Jakarta')

# # Dapatkan waktu saat ini di zona waktu Asia/Jakarta
# waktu_sekarang_ID = datetime.now(tz_ID)

# # Format tanggal dan waktu sesuai keinginan
# tanggal_waktu_ID = waktu_sekarang_ID.strftime("'%d %B %Y %H:%M:%S")

# # Cetak tanggal dan waktu
# print(tanggal_waktu_ID)

# # Merge the two DataFrames on the "Desa" column
# merged_df = pd.merge(df_summary, df2, on="Desa")

# # Print the merged DataFrame
# merged_df.index = merged_df.index + 1
# print(merged_df)

