name: Run Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Set up Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Download ChromeDriver
        run: |
          # CHROME_VERSION=$(google-chrome --version | sed -E 's/Google Chrome ([0-9]+)\..*/\1/')
          # CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
          # wget -N https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
          # CHROME_VERSION=114.0.5735.90
          # wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip -P ~/
          # unzip ~/chromedriver_linux64.zip -d ~/
          # sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          # sudo chmod +x /usr/local/bin/chromedriver
          mkdir ~/chromedriver
          wget -N https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.99/linux64/chrome-linux64.zip -P ~/
          unzip ~/chrome-linux64.zip -d ~/chromedriver
          sudo mv ~/chromedriver /usr/local/bin/
          sudo chmod -R +x /usr/local/bin/chromedriver
        shell: bash

      - name: Install dependencies
        run: |
          pip install selenium
          pip install webdriver-manager
          pip install pandas

      - name: Run Selenium Tests
        run: |
          python pkk_web_scrape.py
